services:
  proxy:
    build: ./servers/proxy
    stdin_open: true
    tty: true
    ports:
      - '25565:25577/tcp'
      - '25565:25577/udp'
      - '19132:19132/udp'
    environment:
      TZ: America/Sao_Paulo
      TYPE: CUSTOM
      BUNGEE_JAR_URL: >-
        https://github.com/UeberallGebannt/KettleCord/releases/download/v6/BungeeCord.jar
      REPLACE_ENV_VARIABLES: 'TRUE'
      ENV_VARIABLE_PREFIX: CFG_
      CFG_DB_HOST: database
      CFG_DB_PORT: '3306'
      CFG_DB_NAME: '${DB_NAME}'
      CFG_DB_USERNAME: '${DB_USERNAME}'
      CFG_DB_PASSWORD: '${DB_PASSWORD}'
  lobby:
    build: ./servers/lobby
    stdin_open: true
    tty: true
    volumes:
      - './worlds/lobby:/data/lobby'
    environment:
      TZ: America/Sao_Paulo
      UID: 1001
      GID: 1001 
      TYPE: PAPER
      ENABLE_AUTOPAUSE: 'FALSE'
      MAX_TICK_TIME: '-1'
      COPY_CONFIG_DEST: /data
      OVERRIDE_SERVER_PROPERTIES: 'TRUE'
      REMOVE_OLD_MODS: 'TRUE'
      USE_AIKAR_FLAGS: 'true'
      ONLINE_MODE: 'FALSE'
      MAX_PLAYERS: '50'
      EULA: 'TRUE'
      OPS: 'misterio'
      MEMORY: 1G
      DIFFICULTY: peaceful
      MODE: adventure
      PVP: 'false'
      SERVER_NAME: lobby
      LEVEL: lobby
      ALLOW_NETHER: 'false'
      SPAWN_ANIMALS: 'false'
      SPAWN_MONSTERS: 'false'
      SPAWN_NPCS: 'false'
      SPAWN_PROTECTION: '999'
      VIEW_DISTANCE: '10'
      LEVEL_TYPE: flat
      ALLOW_FLIGHT: 'true'
      FORCE_GAMEMODE: 'true'
      ENABLE_COMMAND_BLOCK: 'true'
      GENERATE_STRUCTURES: 'false'
      REPLACE_ENV_VARIABLES: 'TRUE'
      ENV_VARIABLE_PREFIX: CFG_
      CFG_BUKKIT_ALLOW_END: 'false'
      CFG_SERVER_NAME: lobby
      CFG_DB_HOST: database
      CFG_DB_PORT: '3306'
      CFG_DB_NAME: '${DB_NAME}'
      CFG_DB_USERNAME: '${DB_USERNAME}'
      CFG_DB_PASSWORD: '${DB_PASSWORD}'
  survival:
    build: ./servers/survival
    stdin_open: true
    tty: true
    volumes:
      - './worlds/survival/world:/data/world'
      - './worlds/survival/world_nether:/data/world_nether'
      - './worlds/survival/world_the_end:/data/world_the_end'
    environment:
      TZ: America/Sao_Paulo
      UID: 1001
      GID: 1001 
      TYPE: PAPER
      ENABLE_AUTOPAUSE: 'TRUE'
      AUTOPAUSE_TIMEOUT_EST: '120'
      AUTOPAUSE_TIMEOUT_INIT: '120'
      AUTOPAUSE_TIMEOUT_KN: '10'
      MAX_TICK_TIME: '-1'
      COPY_CONFIG_DEST: /data
      OVERRIDE_SERVER_PROPERTIES: 'TRUE'
      REMOVE_OLD_MODS: 'TRUE'
      USE_AIKAR_FLAGS: 'true'
      ONLINE_MODE: 'FALSE'
      MAX_PLAYERS: '50'
      EULA: 'TRUE'
      OPS: 'misterio'
      MEMORY: 2G
      DIFFICULTY: normal
      MODE: survival
      PVP: 'true'
      SERVER_NAME: survival
      LEVEL: world
      ALLOW_NETHER: 'true'
      SPAWN_ANIMALS: 'true'
      SPAWN_MONSTERS: 'true'
      SPAWN_NPCS: 'true'
      SPAWN_PROTECTION: '5'
      VIEW_DISTANCE: '10'
      LEVEL_TYPE: default
      ALLOW_FLIGHT: 'true'
      FORCE_GAMEMODE: 'true'
      ENABLE_COMMAND_BLOCK: 'false'
      GENERATE_STRUCTURES: 'true'
      REPLACE_ENV_VARIABLES: 'TRUE'
      ENV_VARIABLE_PREFIX: CFG_
      CFG_BUKKIT_ALLOW_END: 'true'
      CFG_SERVER_NAME: survival
      CFG_DB_HOST: database
      CFG_DB_PORT: '3306'
      CFG_DB_NAME: '${DB_NAME}'
      CFG_DB_USERNAME: '${DB_USERNAME}'
      CFG_DB_PASSWORD: '${DB_PASSWORD}'
  skyblock:
    build: ./servers/skyblock
    stdin_open: true
    tty: true
    volumes:
      - './worlds/skyblock/sblobby:/data/sblobby'
      - './worlds/skyblock/bskyblock_world:/data/bskyblock_world'
      - './worlds/skyblock/bskyblock_world_nether:/data/bskyblock_world_nether'
      - './worlds/skyblock/bskyblock_world_the_end:/data/bskyblock_world_the_end'
    environment:
      TZ: America/Sao_Paulo
      UID: 1001
      GID: 1001 
      TYPE: PAPER
      ENABLE_AUTOPAUSE: 'TRUE'
      AUTOPAUSE_TIMEOUT_EST: '120'
      AUTOPAUSE_TIMEOUT_INIT: '120'
      AUTOPAUSE_TIMEOUT_KN: '10'
      MAX_TICK_TIME: '-1'
      COPY_CONFIG_DEST: /data
      OVERRIDE_SERVER_PROPERTIES: 'TRUE'
      REMOVE_OLD_MODS: 'TRUE'
      USE_AIKAR_FLAGS: 'true'
      ONLINE_MODE: 'FALSE'
      MAX_PLAYERS: '50'
      EULA: 'TRUE'
      OPS: 'misterio'
      MEMORY: 2G
      DIFFICULTY: normal
      MODE: survival
      PVP: 'true'
      SERVER_NAME: skyblock
      LEVEL: sblobby
      ALLOW_NETHER: 'false'
      SPAWN_ANIMALS: 'true'
      SPAWN_MONSTERS: 'true'
      SPAWN_NPCS: 'true'
      SPAWN_PROTECTION: '10'
      VIEW_DISTANCE: '10'
      LEVEL_TYPE: default
      ALLOW_FLIGHT: 'true'
      FORCE_GAMEMODE: 'true'
      ENABLE_COMMAND_BLOCK: 'false'
      GENERATE_STRUCTURES: 'true'
      REPLACE_ENV_VARIABLES: 'TRUE'
      ENV_VARIABLE_PREFIX: CFG_
      CFG_BUKKIT_ALLOW_END: 'false'
      CFG_SERVER_NAME: skyblock
      CFG_DB_HOST: database
      CFG_DB_PORT: '3306'
      CFG_DB_NAME: '${DB_NAME}'
      CFG_DB_USERNAME: '${DB_USERNAME}'
      CFG_DB_PASSWORD: '${DB_PASSWORD}'
  modpack:
    build: ./servers/modpack
    stdin_open: true
    tty: true
    volumes:
      - './worlds/modpack:/data/world'
    environment:
      TZ: America/Sao_Paulo
      UID: 1001
      GID: 1001 
      TYPE: CUSTOM
      VERSION: 1.12.2
      CUSTOM_SERVER: >-
        https://github.com/magmafoundation/Magma/releases/download/vbb50f45/Magma-bb50f45-server.jar
      ENABLE_AUTOPAUSE: 'TRUE'
      AUTOPAUSE_TIMEOUT_EST: '120'
      AUTOPAUSE_TIMEOUT_INIT: '600'
      AUTOPAUSE_TIMEOUT_KN: '10'
      MAX_TICK_TIME: '6000000'
      COPY_CONFIG_DEST: /data
      OVERRIDE_SERVER_PROPERTIES: 'TRUE'
      REMOVE_OLD_MODS: 'TRUE'
      USE_AIKAR_FLAGS: 'true'
      ONLINE_MODE: 'FALSE'
      MAX_PLAYERS: '50'
      EULA: 'TRUE'
      OPS: 'misterio'
      MEMORY: 4G
      DIFFICULTY: normal
      MODE: survival
      PVP: 'true'
      SERVER_NAME: modpack
      LEVEL: world
      ALLOW_NETHER: 'true'
      SPAWN_ANIMALS: 'true'
      SPAWN_MONSTERS: 'true'
      SPAWN_NPCS: 'true'
      SPAWN_PROTECTION: '2'
      VIEW_DISTANCE: '10'
      LEVEL_TYPE: RTG
      ALLOW_FLIGHT: 'true'
      FORCE_GAMEMODE: 'true'
      ENABLE_COMMAND_BLOCK: 'false'
      GENERATE_STRUCTURES: 'true'
      REPLACE_ENV_VARIABLES: 'TRUE'
      ENV_VARIABLE_PREFIX: CFG_
      CFG_BUKKIT_ALLOW_END: 'true'
      CFG_SERVER_NAME: modpack
      CFG_DB_HOST: database
      CFG_DB_PORT: '3306'
      CFG_DB_NAME: '${DB_NAME}'
      CFG_DB_USERNAME: '${DB_USERNAME}'
      CFG_DB_PASSWORD: '${DB_PASSWORD}'
  database:
    image: mariadb
    volumes:
      - './database:/var/lib/mysql'
    environment:
      TZ: America/Sao_Paulo
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
  adminer:
    image: adminer
    ports:
      - '8080:8080'
