services:
    proxy:
        build: "./servers/proxy"
        stdin_open: true
        tty: true
        ports:
            - 25565:25577/tcp
            - 25565:25577/udp
            - 19132:19132/udp
        environment:
            TYPE: "CUSTOM"
            BUNGEE_JAR_URL: "https://github.com/HexagonMC/BungeeCord/releases/download/v268/BungeeCord.jar"
            # Variable replacing
            REPLACE_ENV_VARIABLES: "TRUE"
            ENV_VARIABLE_PREFIX: "CFG_"
            CFG_DB_HOST: "database"
            CFG_DB_PORT: "3306"
            CFG_DB_NAME: "${DB_NAME}"
            CFG_DB_USERNAME: "${DB_USERNAME}"
            CFG_DB_PASSWORD: "${DB_PASSWORD}"
    lobby:
        build: "./servers/lobby"
        stdin_open: true
        tty: true
        volumes:
            - "./worlds/lobby:/data/lobby"
        environment:
            TYPE: "PAPER"
            ENABLE_AUTOPAUSE: "FALSE"
            MAX_TICK_TIME: "-1"
            COPY_CONFIG_DEST: "/data"
            OVERRIDE_SERVER_PROPERTIES: "TRUE"
            REMOVE_OLD_MODS: "TRUE"
            USE_AIKAR_FLAGS: "true"
            ONLINE_MODE: "FALSE"
            MAX_PLAYERS: "50"
            EULA: "TRUE"
            OPS: "misterio8x"
            MEMORY: "1G"
            DIFFICULTY: "peaceful"
            MODE: "adventure"
            PVP: "false"
            SERVER_NAME: "lobby"
            LEVEL: "lobby"
            ALLOW_NETHER: "false"
            SPAWN_ANIMALS: "false"
            SPAWN_MONSTERS: "false"
            SPAWN_NPCS: "false"
            SPAWN_PROTECTION: "999"
            VIEW_DISTANCE: "10"
            LEVEL_TYPE: "flat"
            ALLOW_FLIGHT: "true"
            FORCE_GAMEMODE: "true"
            ENABLE_COMMAND_BLOCK: "true"
            GENERATE_STRUCTURES: "false"
            # Variable replacing
            REPLACE_ENV_VARIABLES: "TRUE"
            ENV_VARIABLE_PREFIX: "CFG_"
            CFG_BUKKIT_ALLOW_END: "false"
            CFG_SERVER_NAME: "lobby"
            CFG_DB_HOST: "database"
            CFG_DB_PORT: "3306"
            CFG_DB_NAME: "${DB_NAME}"
            CFG_DB_USERNAME: "${DB_USERNAME}"
            CFG_DB_PASSWORD: "${DB_PASSWORD}"
    survival:
        build: "./servers/survival"
        stdin_open: true
        tty: true
        volumes:
            - "./worlds/survival/world:/data/world"
            - "./worlds/survival/world_nether:/data/world_nether"
            - "./worlds/survival/world_the_end:/data/world_the_end"
        environment:
            TYPE: "PAPER"
            ENABLE_AUTOPAUSE: "TRUE"
            AUTOPAUSE_TIMEOUT_EST: "120"
            AUTOPAUSE_TIMEOUT_INIT: "120"
            AUTOPAUSE_TIMEOUT_KN: "60"
            MAX_TICK_TIME: "-1"
            COPY_CONFIG_DEST: "/data"
            OVERRIDE_SERVER_PROPERTIES: "TRUE"
            REMOVE_OLD_MODS: "TRUE"
            USE_AIKAR_FLAGS: "true"
            ONLINE_MODE: "FALSE"
            MAX_PLAYERS: "50"
            EULA: "TRUE"
            OPS: "misterio8x"
            MEMORY: "2G"
            DIFFICULTY: "normal"
            MODE: "survival"
            PVP: "true"
            SERVER_NAME: "survival"
            LEVEL: "world"
            ALLOW_NETHER: "true"
            SPAWN_ANIMALS: "true"
            SPAWN_MONSTERS: "true"
            SPAWN_NPCS: "true"
            SPAWN_PROTECTION: "2"
            VIEW_DISTANCE: "10"
            LEVEL_TYPE: "default"
            ALLOW_FLIGHT: "true"
            FORCE_GAMEMODE: "true"
            ENABLE_COMMAND_BLOCK: "false"
            GENERATE_STRUCTURES: "true"
            # Variable replacing
            REPLACE_ENV_VARIABLES: "TRUE"
            ENV_VARIABLE_PREFIX: "CFG_"
            CFG_BUKKIT_ALLOW_END: "true"
            CFG_SERVER_NAME: "survival"
            CFG_DB_HOST: "database"
            CFG_DB_PORT: "3306"
            CFG_DB_NAME: "${DB_NAME}"
            CFG_DB_USERNAME: "${DB_USERNAME}"
            CFG_DB_PASSWORD: "${DB_PASSWORD}"
    modpack:
        build: "./servers/modpack"
        stdin_open: true
        tty: true
        volumes:
            - "./worlds/modpack:/data/world"
        environment:
            TYPE: "CUSTOM"
            VERSION: "1.12.2"
            CUSTOM_SERVER: "https://github.com/magmafoundation/Magma/releases/download/v1656508/Magma-1656508-server.jar"
            ENABLE_AUTOPAUSE: "TRUE"
            AUTOPAUSE_TIMEOUT_EST: "120"
            AUTOPAUSE_TIMEOUT_INIT: "600"
            AUTOPAUSE_TIMEOUT_KN: "60"
            MAX_TICK_TIME: "6000000"
            COPY_CONFIG_DEST: "/data"
            OVERRIDE_SERVER_PROPERTIES: "TRUE"
            REMOVE_OLD_MODS: "TRUE"
            USE_AIKAR_FLAGS: "true"
            ONLINE_MODE: "FALSE"
            MAX_PLAYERS: "50"
            EULA: "TRUE"
            OPS: "misterio8x"
            MEMORY: "4G"
            DIFFICULTY: "normal"
            MODE: "survival"
            PVP: "true"
            SERVER_NAME: "modpack"
            LEVEL: "world"
            ALLOW_NETHER: "true"
            SPAWN_ANIMALS: "true"
            SPAWN_MONSTERS: "true"
            SPAWN_NPCS: "true"
            SPAWN_PROTECTION: "2"
            VIEW_DISTANCE: "10"
            LEVEL_TYPE: "RTG"
            ALLOW_FLIGHT: "true"
            FORCE_GAMEMODE: "true"
            ENABLE_COMMAND_BLOCK: "false"
            GENERATE_STRUCTURES: "true"
            # Variable replacing
            REPLACE_ENV_VARIABLES: "TRUE"
            ENV_VARIABLE_PREFIX: "CFG_"
            CFG_BUKKIT_ALLOW_END: "true"
            CFG_SERVER_NAME: "modpack"
            CFG_DB_HOST: "database"
            CFG_DB_PORT: "3306"
            CFG_DB_NAME: "${DB_NAME}"
            CFG_DB_USERNAME: "${DB_USERNAME}"
            CFG_DB_PASSWORD: "${DB_PASSWORD}"
    modpack-e2es:
        build: "./servers/modpack-e2es"
        stdin_open: true
        tty: true
        volumes:
            - "./worlds/modpack-e2es:/data/world"
        environment:
            TYPE: "CUSTOM"
            VERSION: "1.12.2"
            CUSTOM_SERVER: "https://github.com/magmafoundation/Magma/releases/download/v1656508/Magma-1656508-server.jar"
            ENABLE_AUTOPAUSE: "TRUE"
            AUTOPAUSE_TIMEOUT_EST: "120"
            AUTOPAUSE_TIMEOUT_INIT: "600"
            AUTOPAUSE_TIMEOUT_KN: "60"
            MAX_TICK_TIME: "6000000"
            COPY_CONFIG_DEST: "/data"
            OVERRIDE_SERVER_PROPERTIES: "TRUE"
            REMOVE_OLD_MODS: "TRUE"
            USE_AIKAR_FLAGS: "true"
            ONLINE_MODE: "FALSE"
            MAX_PLAYERS: "50"
            EULA: "TRUE"
            OPS: "misterio8x"
            MEMORY: "4G"
            DIFFICULTY: "normal"
            MODE: "survival"
            PVP: "true"
            SERVER_NAME: "modpack-e2es"
            LEVEL: "world"
            ALLOW_NETHER: "true"
            SPAWN_ANIMALS: "true"
            SPAWN_MONSTERS: "true"
            SPAWN_NPCS: "true"
            SPAWN_PROTECTION: "2"
            VIEW_DISTANCE: "10"
            LEVEL_TYPE: "voidworld"
            ALLOW_FLIGHT: "true"
            FORCE_GAMEMODE: "true"
            ENABLE_COMMAND_BLOCK: "false"
            GENERATE_STRUCTURES: "true"
            # Variable replacing
            REPLACE_ENV_VARIABLES: "TRUE"
            ENV_VARIABLE_PREFIX: "CFG_"
            CFG_BUKKIT_ALLOW_END: "true"
            CFG_SERVER_NAME: "modpack-e2es"
            CFG_DB_HOST: "database"
            CFG_DB_PORT: "3306"
            CFG_DB_NAME: "${DB_NAME}"
            CFG_DB_USERNAME: "${DB_USERNAME}"
     modpack-e2:
        build: "./servers/modpack-e2"
        stdin_open: true
        tty: true
        volumes:
            - "./worlds/modpack-e2:/data/world"
        environment:
            TYPE: "CUSTOM"
            VERSION: "1.12.2"
            CUSTOM_SERVER: "https://github.com/magmafoundation/Magma/releases/download/v1656508/Magma-1656508-server.jar"
            ENABLE_AUTOPAUSE: "TRUE"
            AUTOPAUSE_TIMEOUT_EST: "120"
            AUTOPAUSE_TIMEOUT_INIT: "600"
            AUTOPAUSE_TIMEOUT_KN: "60"
            MAX_TICK_TIME: "6000000"
            COPY_CONFIG_DEST: "/data"
            OVERRIDE_SERVER_PROPERTIES: "TRUE"
            REMOVE_OLD_MODS: "TRUE"
            USE_AIKAR_FLAGS: "true"
            ONLINE_MODE: "FALSE"
            MAX_PLAYERS: "50"
            EULA: "TRUE"
            OPS: "misterio8x"
            MEMORY: "4G"
            DIFFICULTY: "normal"
            MODE: "survival"
            PVP: "true"
            SERVER_NAME: "modpack-e2"
            LEVEL: "world"
            ALLOW_NETHER: "true"
            SPAWN_ANIMALS: "true"
            SPAWN_MONSTERS: "true"
            SPAWN_NPCS: "true"
            SPAWN_PROTECTION: "2"
            VIEW_DISTANCE: "10"
            LEVEL_TYPE: "BIOMESOP"
            ALLOW_FLIGHT: "true"
            FORCE_GAMEMODE: "true"
            ENABLE_COMMAND_BLOCK: "false"
            GENERATE_STRUCTURES: "true"
            # Variable replacing
            REPLACE_ENV_VARIABLES: "TRUE"
            ENV_VARIABLE_PREFIX: "CFG_"
            CFG_BUKKIT_ALLOW_END: "true"
            CFG_SERVER_NAME: "modpack-e2"
            CFG_DB_HOST: "database"
            CFG_DB_PORT: "3306"
            CFG_DB_NAME: "${DB_NAME}"
            CFG_DB_USERNAME: "${DB_USERNAME}"
            CFG_DB_PASSWORD: "${DB_PASSWORD}"
           CFG_DB_PASSWORD: "${DB_PASSWORD}"
    database:
        image: mariadb
        volumes:
            - "./database:/var/lib/mysql"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
    adminer:
        image: adminer
        ports:
            - 8080:8080
